/*
 * Copyright (C) 2023 Flavio Faria
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.flaviofaria.catalog.gradle.codegen.writer

import com.flaviofaria.catalog.gradle.codegen.ResourceEntry
import com.google.common.truth.Truth.assertThat
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File
import java.nio.charset.Charset

class ColorCatalogWriterTest {

  @get:Rule
  var folder = TemporaryFolder()

  private lateinit var codegenDestination: File

  private val resources = listOf(
    ResourceEntry.Color(
      file = File("."),
      name = "color_1",
      docs = "Color 1 docs",
    ),
    ResourceEntry.Color(
      file = File("."),
      name = "color_2",
      docs = null,
    ),
  )

  @Before
  fun setUp() {
    codegenDestination = folder.newFolder()
  }

  @Test
  fun `GIVEN generateResourcesExtensions and generateComposeExtensions disabled THEN generate property extensions only`() {
    val codegenFile = File("${codegenDestination.absolutePath}/com/example/Colors.kt")
    val writer = ColorCatalogWriter(
      packageName = "com.example",
    )
    writer.write(
      resources,
      sourceSetName = "main",
      codegenDestination = codegenDestination,
      generateResourcesExtensions = false,
      generateComposeExtensions = false,
    )
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualTo(
      """
      |// Auto-generated by Catalog. DO NOT EDIT.
      |// https://github.com/flavioarfaria/Catalog
      |@file:JvmName("ColorsMain")
      |@file:Suppress("NOTHING_TO_INLINE")
      |
      |package com.example
      |
      |import com.flaviofaria.catalog.runtime.resources.Colors
      |import kotlin.Int
      |import kotlin.Suppress
      |import kotlin.jvm.JvmName
      |
      |/**
      | * Color 1 docs
      | */
      |public inline val Colors.color1: Int
      |  get() = R.color.color_1
      |
      |public inline val Colors.color2: Int
      |  get() = R.color.color_2
      |""".trimMargin(),
    )
  }

  @Test
  fun `GIVEN generateResourcesExtensions enabled and generateComposeExtensions disabled THEN generate property and resources extensions only`() {
    val codegenFile = File("${codegenDestination.absolutePath}/com/example/Colors.kt")
    val writer = ColorCatalogWriter(
      packageName = "com.example",
    )
    writer.write(
      resources,
      sourceSetName = "main",
      codegenDestination = codegenDestination,
      generateResourcesExtensions = true,
      generateComposeExtensions = false,
    )
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualTo(
      """
      |// Auto-generated by Catalog. DO NOT EDIT.
      |// https://github.com/flavioarfaria/Catalog
      |@file:JvmName("ColorsMain")
      |@file:Suppress("NOTHING_TO_INLINE")
      |
      |package com.example
      |
      |import android.content.Context
      |import android.graphics.Color
      |import androidx.core.content.ContextCompat
      |import androidx.fragment.app.Fragment
      |import com.flaviofaria.catalog.runtime.resources.Colors
      |import kotlin.Int
      |import kotlin.Suppress
      |import kotlin.jvm.JvmName
      |
      |/**
      | * Color 1 docs
      | */
      |public inline val Colors.color1: Int
      |  get() = R.color.color_1
      |
      |/**
      | * Color 1 docs
      | */
      |context(Context)
      |public inline fun Colors.color1(): Color = Color.valueOf(ContextCompat.getColor(this@Context,
      |    R.color.color_1))
      |
      |/**
      | * Color 1 docs
      | */
      |context(Fragment)
      |public inline fun Colors.color1(): Color = Color.valueOf(ContextCompat.getColor(requireContext(),
      |    R.color.color_1))
      |
      |public inline val Colors.color2: Int
      |  get() = R.color.color_2
      |
      |context(Context)
      |public inline fun Colors.color2(): Color = Color.valueOf(ContextCompat.getColor(this@Context,
      |    R.color.color_2))
      |
      |context(Fragment)
      |public inline fun Colors.color2(): Color = Color.valueOf(ContextCompat.getColor(requireContext(),
      |    R.color.color_2))
      |""".trimMargin(),
    )
  }

  @Test
  fun `GIVEN generateResourcesExtensions disabled and generateComposeExtensions enabled THEN generate property and compose extensions only`() {
    val codegenFile = File("${codegenDestination.absolutePath}/com/example/Colors.kt")
    val writer = ColorCatalogWriter(
      packageName = "com.example",
    )
    writer.write(
      resources,
      sourceSetName = "main",
      codegenDestination = codegenDestination,
      generateResourcesExtensions = false,
      generateComposeExtensions = true,
    )
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualTo(
      """
      |// Auto-generated by Catalog. DO NOT EDIT.
      |// https://github.com/flavioarfaria/Catalog
      |@file:JvmName("ColorsMain")
      |@file:Suppress("NOTHING_TO_INLINE")
      |
      |package com.example
      |
      |import androidx.compose.runtime.Composable
      |import androidx.compose.runtime.ReadOnlyComposable
      |import androidx.compose.ui.graphics.Color
      |import androidx.compose.ui.res.colorResource
      |import com.flaviofaria.catalog.runtime.compose.Colors
      |import kotlin.Int
      |import kotlin.Suppress
      |import kotlin.jvm.JvmName
      |
      |/**
      | * Color 1 docs
      | */
      |public inline val Colors.color1: Int
      |  get() = R.color.color_1
      |
      |/**
      | * Color 1 docs
      | */
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Colors.color1(): Color = colorResource(R.color.color_1)
      |
      |public inline val Colors.color2: Int
      |  get() = R.color.color_2
      |
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Colors.color2(): Color = colorResource(R.color.color_2)
      |""".trimMargin(),
    )
  }

  @Test
  fun `GIVEN generateResources and generateComposeExtensions enabled THEN generate property, resources and compose extensions`() {
    val codegenFile = File("${codegenDestination.absolutePath}/com/example/Colors.kt")
    val writer = ColorCatalogWriter(
      packageName = "com.example",
    )
    writer.write(
      resources,
      sourceSetName = "main",
      codegenDestination = codegenDestination,
      generateResourcesExtensions = true,
      generateComposeExtensions = true,
    )
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualTo(
      """
      |// Auto-generated by Catalog. DO NOT EDIT.
      |// https://github.com/flavioarfaria/Catalog
      |@file:JvmName("ColorsMain")
      |@file:Suppress("NOTHING_TO_INLINE")
      |
      |package com.example
      |
      |import android.content.Context
      |import android.graphics.Color
      |import androidx.compose.runtime.Composable
      |import androidx.compose.runtime.ReadOnlyComposable
      |import androidx.compose.ui.res.colorResource
      |import androidx.core.content.ContextCompat
      |import androidx.fragment.app.Fragment
      |import com.flaviofaria.catalog.runtime.compose.Colors
      |import kotlin.Int
      |import kotlin.Suppress
      |import kotlin.jvm.JvmName
      |
      |/**
      | * Color 1 docs
      | */
      |public inline val Colors.color1: Int
      |  get() = R.color.color_1
      |
      |/**
      | * Color 1 docs
      | */
      |context(Context)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Colors.color1(): Color =
      |    Color.valueOf(ContextCompat.getColor(this@Context, R.color.color_1))
      |
      |/**
      | * Color 1 docs
      | */
      |context(Fragment)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Colors.color1(): Color =
      |    Color.valueOf(ContextCompat.getColor(requireContext(), R.color.color_1))
      |
      |/**
      | * Color 1 docs
      | */
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Colors.color1(): androidx.compose.ui.graphics.Color =
      |    colorResource(R.color.color_1)
      |
      |public inline val Colors.color2: Int
      |  get() = R.color.color_2
      |
      |context(Context)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Colors.color2(): Color =
      |    Color.valueOf(ContextCompat.getColor(this@Context, R.color.color_2))
      |
      |context(Fragment)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Colors.color2(): Color =
      |    Color.valueOf(ContextCompat.getColor(requireContext(), R.color.color_2))
      |
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Colors.color2(): androidx.compose.ui.graphics.Color =
      |    colorResource(R.color.color_2)
      |""".trimMargin(),
    )
  }
}
