/*
 * Copyright (C) 2022 Flavio Faria
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.flaviofaria.catalog.gradle.codegen.writer

import com.flaviofaria.catalog.gradle.codegen.ResourceEntry
import com.flaviofaria.catalog.gradle.codegen.ResourceType
import com.flaviofaria.catalog.gradle.codegen.StringArg
import com.google.common.truth.Truth.assertThat
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File
import java.nio.charset.Charset

class WithArgsCatalogWriterTest {

  @get:Rule
  var folder = TemporaryFolder()

  private lateinit var codegenDestination: File

  private val stringResources = listOf(
    ResourceEntry.XmlItem.WithArgs.String(
      file = File("."),
      name = "string_1",
      docs = "String 1 docs",
      args = emptyList(),
    ),
    ResourceEntry.XmlItem.WithArgs.String(
      file = File("."),
      name = "string_2",
      docs = null,
      args = listOf(
        StringArg(
          position = 1,
          type = 'd',
        ),
        StringArg(
          position = 2,
          type = 'i',
        ),
        StringArg(
          position = 3,
          type = 'u',
        ),
        StringArg(
          position = 4,
          type = 'x',
        ),
        StringArg(
          position = 5,
          type = 'o',
        ),
      ),
    ),
    ResourceEntry.XmlItem.WithArgs.String(
      file = File("."),
      name = "string_3",
      docs = null,
      args = listOf(
        StringArg(
          position = 1,
          type = 'f',
        ),
        StringArg(
          position = 2,
          type = 'e',
        ),
        StringArg(
          position = 3,
          type = 'g',
        ),
        StringArg(
          position = 4,
          type = 'a',
        ),
        StringArg(
          position = 5,
          type = 's',
        ),
      ),
    ),
    ResourceEntry.XmlItem.WithArgs.String(
      file = File("."),
      name = "string_4",
      docs = null,
      args = listOf(
        StringArg(
          position = 1,
          type = 'c',
        ),
      ),
    ),
  )

  private val pluralResources = listOf(
    ResourceEntry.XmlItem.WithArgs.Plural(
      file = File("."),
      name = "plural_1",
      docs = "Plural 1 docs",
      args = emptyList(),
    ),
    ResourceEntry.XmlItem.WithArgs.Plural(
      file = File("."),
      name = "plural_2",
      docs = null,
      args = listOf(
        StringArg(
          position = 1,
          type = 'd',
        ),
        StringArg(
          position = 2,
          type = 'i',
        ),
        StringArg(
          position = 3,
          type = 'u',
        ),
        StringArg(
          position = 4,
          type = 'x',
        ),
        StringArg(
          position = 5,
          type = 'o',
        ),
      ),
    ),
    ResourceEntry.XmlItem.WithArgs.Plural(
      file = File("."),
      name = "plural_3",
      docs = null,
      args = listOf(
        StringArg(
          position = 1,
          type = 'f',
        ),
        StringArg(
          position = 2,
          type = 'e',
        ),
        StringArg(
          position = 3,
          type = 'g',
        ),
        StringArg(
          position = 4,
          type = 'a',
        ),
        StringArg(
          position = 5,
          type = 's',
        ),
      ),
    ),
    ResourceEntry.XmlItem.WithArgs.Plural(
      file = File("."),
      name = "plural_4",
      docs = null,
      args = listOf(
        StringArg(
          position = 1,
          type = 'c',
        ),
      ),
    ),
  )

  @Before
  fun setUp() {
    codegenDestination = folder.newFolder()
  }

  @Test
  fun `GIVEN resource type String, generateResourcesExtensions and generateComposeExtensions disabled THEN generate property extensions only`() {
    val codegenFile = File("${codegenDestination.absolutePath}/com/example/Strings.kt")
    val writer = WithArgsCatalogWriter(
      packageName = "com.example",
      resourceType = ResourceType.String,
    )
    writer.write(
      stringResources,
      sourceSetName = "main",
      codegenDestination = codegenDestination,
      generateResourcesExtensions = false,
      generateComposeExtensions = false,
    )
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualTo(
      """
      |// Auto-generated by Catalog. DO NOT EDIT.
      |// https://github.com/flavioarfaria/Catalog
      |@file:JvmName("StringsMain")
      |@file:Suppress("NOTHING_TO_INLINE")
      |
      |package com.example
      |
      |import androidx.`annotation`.StringRes
      |import com.flaviofaria.catalog.runtime.resources.Strings
      |import kotlin.Int
      |import kotlin.Suppress
      |import kotlin.jvm.JvmName
      |
      |/**
      | * String 1 docs
      | */
      |@get:StringRes
      |public inline val Strings.string1: Int
      |  get() = R.string.string_1
      |
      |@get:StringRes
      |public inline val Strings.string2: Int
      |  get() = R.string.string_2
      |
      |@get:StringRes
      |public inline val Strings.string3: Int
      |  get() = R.string.string_3
      |
      |@get:StringRes
      |public inline val Strings.string4: Int
      |  get() = R.string.string_4
      |""".trimMargin(),
    )
  }

  @Test
  fun `GIVEN resource type Plural, generateResourcesExtensions and generateComposeExtensions disabled THEN generate property extensions only`() {
    val codegenFile = File("${codegenDestination.absolutePath}/com/example/Plurals.kt")
    val writer = WithArgsCatalogWriter(
      packageName = "com.example",
      resourceType = ResourceType.Plural,
    )
    writer.write(
      pluralResources,
      sourceSetName = "main",
      codegenDestination = codegenDestination,
      generateResourcesExtensions = false,
      generateComposeExtensions = false,
    )
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualTo(
      """
      |// Auto-generated by Catalog. DO NOT EDIT.
      |// https://github.com/flavioarfaria/Catalog
      |@file:JvmName("PluralsMain")
      |@file:Suppress("NOTHING_TO_INLINE")
      |
      |package com.example
      |
      |import androidx.`annotation`.PluralsRes
      |import com.flaviofaria.catalog.runtime.resources.Plurals
      |import kotlin.Int
      |import kotlin.Suppress
      |import kotlin.jvm.JvmName
      |
      |/**
      | * Plural 1 docs
      | */
      |@get:PluralsRes
      |public inline val Plurals.plural1: Int
      |  get() = R.plurals.plural_1
      |
      |@get:PluralsRes
      |public inline val Plurals.plural2: Int
      |  get() = R.plurals.plural_2
      |
      |@get:PluralsRes
      |public inline val Plurals.plural3: Int
      |  get() = R.plurals.plural_3
      |
      |@get:PluralsRes
      |public inline val Plurals.plural4: Int
      |  get() = R.plurals.plural_4
      |""".trimMargin(),
    )
  }

  @Test
  fun `GIVEN resource type String, generateResourcesExtensions enabled and generateComposeExtensions disabled THEN generate property and resources extensions only`() {
    val codegenFile = File("${codegenDestination.absolutePath}/com/example/Strings.kt")
    val writer = WithArgsCatalogWriter(
      packageName = "com.example",
      resourceType = ResourceType.String,
    )
    writer.write(
      stringResources,
      sourceSetName = "main",
      codegenDestination = codegenDestination,
      generateResourcesExtensions = true,
      generateComposeExtensions = false,
    )
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualTo(
      """
      |// Auto-generated by Catalog. DO NOT EDIT.
      |// https://github.com/flavioarfaria/Catalog
      |@file:JvmName("StringsMain")
      |@file:Suppress("NOTHING_TO_INLINE")
      |
      |package com.example
      |
      |import android.content.Context
      |import androidx.`annotation`.StringRes
      |import androidx.fragment.app.Fragment
      |import com.flaviofaria.catalog.runtime.resources.Strings
      |import kotlin.Char
      |import kotlin.CharSequence
      |import kotlin.Double
      |import kotlin.Int
      |import kotlin.String
      |import kotlin.Suppress
      |import kotlin.UInt
      |import kotlin.jvm.JvmName
      |
      |/**
      | * String 1 docs
      | */
      |@get:StringRes
      |public inline val Strings.string1: Int
      |  get() = R.string.string_1
      |
      |/**
      | * String 1 docs
      | */
      |context(Context)
      |public inline fun Strings.string1(): CharSequence = getText(R.string.string_1)
      |
      |/**
      | * String 1 docs
      | */
      |context(Fragment)
      |public inline fun Strings.string1(): CharSequence = getText(R.string.string_1)
      |
      |@get:StringRes
      |public inline val Strings.string2: Int
      |  get() = R.string.string_2
      |
      |context(Context)
      |public inline fun Strings.string2(
      |  arg1: Int,
      |  arg2: Int,
      |  arg3: UInt,
      |  arg4: UInt,
      |  arg5: UInt,
      |): String = getString(R.string.string_2, arg1, arg2, arg3, arg4, arg5)
      |
      |context(Fragment)
      |public inline fun Strings.string2(
      |  arg1: Int,
      |  arg2: Int,
      |  arg3: UInt,
      |  arg4: UInt,
      |  arg5: UInt,
      |): String = getString(R.string.string_2, arg1, arg2, arg3, arg4, arg5)
      |
      |@get:StringRes
      |public inline val Strings.string3: Int
      |  get() = R.string.string_3
      |
      |context(Context)
      |public inline fun Strings.string3(
      |  arg1: Double,
      |  arg2: Double,
      |  arg3: Double,
      |  arg4: Double,
      |  arg5: String,
      |): String = getString(R.string.string_3, arg1, arg2, arg3, arg4, arg5)
      |
      |context(Fragment)
      |public inline fun Strings.string3(
      |  arg1: Double,
      |  arg2: Double,
      |  arg3: Double,
      |  arg4: Double,
      |  arg5: String,
      |): String = getString(R.string.string_3, arg1, arg2, arg3, arg4, arg5)
      |
      |@get:StringRes
      |public inline val Strings.string4: Int
      |  get() = R.string.string_4
      |
      |context(Context)
      |public inline fun Strings.string4(arg1: Char): String = getString(R.string.string_4, arg1)
      |
      |context(Fragment)
      |public inline fun Strings.string4(arg1: Char): String = getString(R.string.string_4, arg1)
      |""".trimMargin(),
    )
  }

  @Test
  fun `GIVEN resource type Plural, generateResourcesExtensions enabled and generateComposeExtensions disabled THEN generate property and resources extensions only`() {
    val codegenFile = File("${codegenDestination.absolutePath}/com/example/Plurals.kt")
    val writer = WithArgsCatalogWriter(
      packageName = "com.example",
      resourceType = ResourceType.Plural,
    )
    writer.write(
      pluralResources,
      sourceSetName = "main",
      codegenDestination = codegenDestination,
      generateResourcesExtensions = true,
      generateComposeExtensions = false,
    )
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualTo(
      """
      |// Auto-generated by Catalog. DO NOT EDIT.
      |// https://github.com/flavioarfaria/Catalog
      |@file:JvmName("PluralsMain")
      |@file:Suppress("NOTHING_TO_INLINE")
      |
      |package com.example
      |
      |import android.content.Context
      |import androidx.`annotation`.PluralsRes
      |import androidx.fragment.app.Fragment
      |import com.flaviofaria.catalog.runtime.resources.Plurals
      |import kotlin.Char
      |import kotlin.CharSequence
      |import kotlin.Double
      |import kotlin.Int
      |import kotlin.String
      |import kotlin.Suppress
      |import kotlin.UInt
      |import kotlin.jvm.JvmName
      |
      |/**
      | * Plural 1 docs
      | */
      |@get:PluralsRes
      |public inline val Plurals.plural1: Int
      |  get() = R.plurals.plural_1
      |
      |/**
      | * Plural 1 docs
      | */
      |context(Context)
      |public inline fun Plurals.plural1(quantity: Int): CharSequence =
      |    resources.getQuantityString(R.plurals.plural_1, quantity)
      |
      |/**
      | * Plural 1 docs
      | */
      |context(Fragment)
      |public inline fun Plurals.plural1(quantity: Int): CharSequence =
      |    resources.getQuantityString(R.plurals.plural_1, quantity)
      |
      |@get:PluralsRes
      |public inline val Plurals.plural2: Int
      |  get() = R.plurals.plural_2
      |
      |context(Context)
      |public inline fun Plurals.plural2(
      |  quantity: Int,
      |  arg1: Int,
      |  arg2: Int,
      |  arg3: UInt,
      |  arg4: UInt,
      |  arg5: UInt,
      |): String = resources.getQuantityString(R.plurals.plural_2, quantity, arg1, arg2, arg3, arg4, arg5)
      |
      |context(Fragment)
      |public inline fun Plurals.plural2(
      |  quantity: Int,
      |  arg1: Int,
      |  arg2: Int,
      |  arg3: UInt,
      |  arg4: UInt,
      |  arg5: UInt,
      |): String = resources.getQuantityString(R.plurals.plural_2, quantity, arg1, arg2, arg3, arg4, arg5)
      |
      |@get:PluralsRes
      |public inline val Plurals.plural3: Int
      |  get() = R.plurals.plural_3
      |
      |context(Context)
      |public inline fun Plurals.plural3(
      |  quantity: Int,
      |  arg1: Double,
      |  arg2: Double,
      |  arg3: Double,
      |  arg4: Double,
      |  arg5: String,
      |): String = resources.getQuantityString(R.plurals.plural_3, quantity, arg1, arg2, arg3, arg4, arg5)
      |
      |context(Fragment)
      |public inline fun Plurals.plural3(
      |  quantity: Int,
      |  arg1: Double,
      |  arg2: Double,
      |  arg3: Double,
      |  arg4: Double,
      |  arg5: String,
      |): String = resources.getQuantityString(R.plurals.plural_3, quantity, arg1, arg2, arg3, arg4, arg5)
      |
      |@get:PluralsRes
      |public inline val Plurals.plural4: Int
      |  get() = R.plurals.plural_4
      |
      |context(Context)
      |public inline fun Plurals.plural4(quantity: Int, arg1: Char): String =
      |    resources.getQuantityString(R.plurals.plural_4, quantity, arg1)
      |
      |context(Fragment)
      |public inline fun Plurals.plural4(quantity: Int, arg1: Char): String =
      |    resources.getQuantityString(R.plurals.plural_4, quantity, arg1)
      |""".trimMargin(),
    )
  }

  @Test
  fun `GIVEN resource type String, generateResourcesExtensions disabled and generateComposeExtensions enabled THEN generate property and compose extensions only`() {
    val codegenFile = File("${codegenDestination.absolutePath}/com/example/Strings.kt")
    val writer = WithArgsCatalogWriter(
      packageName = "com.example",
      resourceType = ResourceType.String,
    )
    writer.write(
      stringResources,
      sourceSetName = "main",
      codegenDestination = codegenDestination,
      generateResourcesExtensions = false,
      generateComposeExtensions = true,
    )
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualTo(
      """
      |// Auto-generated by Catalog. DO NOT EDIT.
      |// https://github.com/flavioarfaria/Catalog
      |@file:JvmName("StringsMain")
      |@file:Suppress("NOTHING_TO_INLINE")
      |
      |package com.example
      |
      |import androidx.`annotation`.StringRes
      |import androidx.compose.runtime.Composable
      |import androidx.compose.runtime.ReadOnlyComposable
      |import androidx.compose.ui.res.stringResource
      |import com.flaviofaria.catalog.runtime.compose.Strings
      |import kotlin.Char
      |import kotlin.CharSequence
      |import kotlin.Double
      |import kotlin.Int
      |import kotlin.String
      |import kotlin.Suppress
      |import kotlin.UInt
      |import kotlin.jvm.JvmName
      |
      |/**
      | * String 1 docs
      | */
      |@get:StringRes
      |public inline val Strings.string1: Int
      |  get() = R.string.string_1
      |
      |/**
      | * String 1 docs
      | */
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Strings.string1(): CharSequence = stringResource(R.string.string_1)
      |
      |@get:StringRes
      |public inline val Strings.string2: Int
      |  get() = R.string.string_2
      |
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Strings.string2(
      |  arg1: Int,
      |  arg2: Int,
      |  arg3: UInt,
      |  arg4: UInt,
      |  arg5: UInt,
      |): String = stringResource(R.string.string_2, arg1, arg2, arg3, arg4, arg5)
      |
      |@get:StringRes
      |public inline val Strings.string3: Int
      |  get() = R.string.string_3
      |
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Strings.string3(
      |  arg1: Double,
      |  arg2: Double,
      |  arg3: Double,
      |  arg4: Double,
      |  arg5: String,
      |): String = stringResource(R.string.string_3, arg1, arg2, arg3, arg4, arg5)
      |
      |@get:StringRes
      |public inline val Strings.string4: Int
      |  get() = R.string.string_4
      |
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Strings.string4(arg1: Char): String = stringResource(R.string.string_4, arg1)
      |""".trimMargin(),
    )
  }

  @Test
  fun `GIVEN resource type Plural, generateResourcesExtensions disabled and generateComposeExtensions enabled THEN generate property and compose extensions only`() {
    val codegenFile = File("${codegenDestination.absolutePath}/com/example/Plurals.kt")
    val writer = WithArgsCatalogWriter(
      packageName = "com.example",
      resourceType = ResourceType.Plural,
    )
    writer.write(
      pluralResources,
      sourceSetName = "main",
      codegenDestination = codegenDestination,
      generateResourcesExtensions = false,
      generateComposeExtensions = true,
    )
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualTo(
      """
      |// Auto-generated by Catalog. DO NOT EDIT.
      |// https://github.com/flavioarfaria/Catalog
      |@file:JvmName("PluralsMain")
      |@file:Suppress("NOTHING_TO_INLINE")
      |
      |package com.example
      |
      |import androidx.`annotation`.PluralsRes
      |import androidx.compose.runtime.Composable
      |import androidx.compose.runtime.ReadOnlyComposable
      |import androidx.compose.ui.ExperimentalComposeUiApi
      |import androidx.compose.ui.res.pluralStringResource
      |import com.flaviofaria.catalog.runtime.compose.Plurals
      |import kotlin.Char
      |import kotlin.CharSequence
      |import kotlin.Double
      |import kotlin.Int
      |import kotlin.OptIn
      |import kotlin.String
      |import kotlin.Suppress
      |import kotlin.UInt
      |import kotlin.jvm.JvmName
      |
      |/**
      | * Plural 1 docs
      | */
      |@get:PluralsRes
      |public inline val Plurals.plural1: Int
      |  get() = R.plurals.plural_1
      |
      |/**
      | * Plural 1 docs
      | */
      |@OptIn(ExperimentalComposeUiApi::class)
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Plurals.plural1(quantity: Int): CharSequence =
      |    pluralStringResource(R.plurals.plural_1, quantity)
      |
      |@get:PluralsRes
      |public inline val Plurals.plural2: Int
      |  get() = R.plurals.plural_2
      |
      |@OptIn(ExperimentalComposeUiApi::class)
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Plurals.plural2(
      |  quantity: Int,
      |  arg1: Int,
      |  arg2: Int,
      |  arg3: UInt,
      |  arg4: UInt,
      |  arg5: UInt,
      |): String = pluralStringResource(R.plurals.plural_2, quantity, arg1, arg2, arg3, arg4, arg5)
      |
      |@get:PluralsRes
      |public inline val Plurals.plural3: Int
      |  get() = R.plurals.plural_3
      |
      |@OptIn(ExperimentalComposeUiApi::class)
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Plurals.plural3(
      |  quantity: Int,
      |  arg1: Double,
      |  arg2: Double,
      |  arg3: Double,
      |  arg4: Double,
      |  arg5: String,
      |): String = pluralStringResource(R.plurals.plural_3, quantity, arg1, arg2, arg3, arg4, arg5)
      |
      |@get:PluralsRes
      |public inline val Plurals.plural4: Int
      |  get() = R.plurals.plural_4
      |
      |@OptIn(ExperimentalComposeUiApi::class)
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Plurals.plural4(quantity: Int, arg1: Char): String =
      |    pluralStringResource(R.plurals.plural_4, quantity, arg1)
      |""".trimMargin(),
    )
  }

  @Test
  fun `GIVEN resource type String, generateResourcesExtensions and generateComposeExtensions enabled THEN generate property, resources and compose extensions`() {
    val codegenFile = File("${codegenDestination.absolutePath}/com/example/Strings.kt")
    val writer = WithArgsCatalogWriter(
      packageName = "com.example",
      resourceType = ResourceType.String,
    )
    writer.write(
      stringResources,
      sourceSetName = "main",
      codegenDestination = codegenDestination,
      generateResourcesExtensions = true,
      generateComposeExtensions = true,
    )
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualTo(
      """
      |// Auto-generated by Catalog. DO NOT EDIT.
      |// https://github.com/flavioarfaria/Catalog
      |@file:JvmName("StringsMain")
      |@file:Suppress("NOTHING_TO_INLINE")
      |
      |package com.example
      |
      |import android.content.Context
      |import androidx.`annotation`.StringRes
      |import androidx.compose.runtime.Composable
      |import androidx.compose.runtime.ReadOnlyComposable
      |import androidx.compose.ui.res.stringResource
      |import androidx.fragment.app.Fragment
      |import com.flaviofaria.catalog.runtime.compose.Strings
      |import kotlin.Char
      |import kotlin.CharSequence
      |import kotlin.Double
      |import kotlin.Int
      |import kotlin.String
      |import kotlin.Suppress
      |import kotlin.UInt
      |import kotlin.jvm.JvmName
      |
      |/**
      | * String 1 docs
      | */
      |@get:StringRes
      |public inline val Strings.string1: Int
      |  get() = R.string.string_1
      |
      |/**
      | * String 1 docs
      | */
      |context(Context)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Strings.string1(): CharSequence =
      |    getText(R.string.string_1)
      |
      |/**
      | * String 1 docs
      | */
      |context(Fragment)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Strings.string1(): CharSequence =
      |    getText(R.string.string_1)
      |
      |/**
      | * String 1 docs
      | */
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Strings.string1(): CharSequence = stringResource(R.string.string_1)
      |
      |@get:StringRes
      |public inline val Strings.string2: Int
      |  get() = R.string.string_2
      |
      |context(Context)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Strings.string2(
      |  arg1: Int,
      |  arg2: Int,
      |  arg3: UInt,
      |  arg4: UInt,
      |  arg5: UInt,
      |): String = getString(R.string.string_2, arg1, arg2, arg3, arg4, arg5)
      |
      |context(Fragment)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Strings.string2(
      |  arg1: Int,
      |  arg2: Int,
      |  arg3: UInt,
      |  arg4: UInt,
      |  arg5: UInt,
      |): String = getString(R.string.string_2, arg1, arg2, arg3, arg4, arg5)
      |
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Strings.string2(
      |  arg1: Int,
      |  arg2: Int,
      |  arg3: UInt,
      |  arg4: UInt,
      |  arg5: UInt,
      |): String = stringResource(R.string.string_2, arg1, arg2, arg3, arg4, arg5)
      |
      |@get:StringRes
      |public inline val Strings.string3: Int
      |  get() = R.string.string_3
      |
      |context(Context)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Strings.string3(
      |  arg1: Double,
      |  arg2: Double,
      |  arg3: Double,
      |  arg4: Double,
      |  arg5: String,
      |): String = getString(R.string.string_3, arg1, arg2, arg3, arg4, arg5)
      |
      |context(Fragment)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Strings.string3(
      |  arg1: Double,
      |  arg2: Double,
      |  arg3: Double,
      |  arg4: Double,
      |  arg5: String,
      |): String = getString(R.string.string_3, arg1, arg2, arg3, arg4, arg5)
      |
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Strings.string3(
      |  arg1: Double,
      |  arg2: Double,
      |  arg3: Double,
      |  arg4: Double,
      |  arg5: String,
      |): String = stringResource(R.string.string_3, arg1, arg2, arg3, arg4, arg5)
      |
      |@get:StringRes
      |public inline val Strings.string4: Int
      |  get() = R.string.string_4
      |
      |context(Context)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Strings.string4(arg1: Char): String =
      |    getString(R.string.string_4, arg1)
      |
      |context(Fragment)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Strings.string4(arg1: Char): String =
      |    getString(R.string.string_4, arg1)
      |
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Strings.string4(arg1: Char): String = stringResource(R.string.string_4, arg1)
      |""".trimMargin(),
    )
  }

  @Test
  fun `GIVEN resource type Plural, generateResourcesExtensions and generateComposeExtensions enabled THEN generate property, resources and compose extensions`() {
    val codegenFile = File("${codegenDestination.absolutePath}/com/example/Plurals.kt")
    val writer = WithArgsCatalogWriter(
      packageName = "com.example",
      resourceType = ResourceType.Plural,
    )
    writer.write(
      pluralResources,
      sourceSetName = "main",
      codegenDestination = codegenDestination,
      generateResourcesExtensions = true,
      generateComposeExtensions = true,
    )
    assertThat(
      codegenFile.readBytes().toString(Charset.defaultCharset()),
    ).isEqualTo(
      """
      |// Auto-generated by Catalog. DO NOT EDIT.
      |// https://github.com/flavioarfaria/Catalog
      |@file:JvmName("PluralsMain")
      |@file:Suppress("NOTHING_TO_INLINE")
      |
      |package com.example
      |
      |import android.content.Context
      |import androidx.`annotation`.PluralsRes
      |import androidx.compose.runtime.Composable
      |import androidx.compose.runtime.ReadOnlyComposable
      |import androidx.compose.ui.ExperimentalComposeUiApi
      |import androidx.compose.ui.res.pluralStringResource
      |import androidx.fragment.app.Fragment
      |import com.flaviofaria.catalog.runtime.compose.Plurals
      |import kotlin.Char
      |import kotlin.CharSequence
      |import kotlin.Double
      |import kotlin.Int
      |import kotlin.OptIn
      |import kotlin.String
      |import kotlin.Suppress
      |import kotlin.UInt
      |import kotlin.jvm.JvmName
      |
      |/**
      | * Plural 1 docs
      | */
      |@get:PluralsRes
      |public inline val Plurals.plural1: Int
      |  get() = R.plurals.plural_1
      |
      |/**
      | * Plural 1 docs
      | */
      |context(Context)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Plurals.plural1(quantity: Int):
      |    CharSequence = resources.getQuantityString(R.plurals.plural_1, quantity)
      |
      |/**
      | * Plural 1 docs
      | */
      |context(Fragment)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Plurals.plural1(quantity: Int):
      |    CharSequence = resources.getQuantityString(R.plurals.plural_1, quantity)
      |
      |/**
      | * Plural 1 docs
      | */
      |@OptIn(ExperimentalComposeUiApi::class)
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Plurals.plural1(quantity: Int): CharSequence =
      |    pluralStringResource(R.plurals.plural_1, quantity)
      |
      |@get:PluralsRes
      |public inline val Plurals.plural2: Int
      |  get() = R.plurals.plural_2
      |
      |context(Context)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Plurals.plural2(
      |  quantity: Int,
      |  arg1: Int,
      |  arg2: Int,
      |  arg3: UInt,
      |  arg4: UInt,
      |  arg5: UInt,
      |): String = resources.getQuantityString(R.plurals.plural_2, quantity, arg1, arg2, arg3, arg4, arg5)
      |
      |context(Fragment)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Plurals.plural2(
      |  quantity: Int,
      |  arg1: Int,
      |  arg2: Int,
      |  arg3: UInt,
      |  arg4: UInt,
      |  arg5: UInt,
      |): String = resources.getQuantityString(R.plurals.plural_2, quantity, arg1, arg2, arg3, arg4, arg5)
      |
      |@OptIn(ExperimentalComposeUiApi::class)
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Plurals.plural2(
      |  quantity: Int,
      |  arg1: Int,
      |  arg2: Int,
      |  arg3: UInt,
      |  arg4: UInt,
      |  arg5: UInt,
      |): String = pluralStringResource(R.plurals.plural_2, quantity, arg1, arg2, arg3, arg4, arg5)
      |
      |@get:PluralsRes
      |public inline val Plurals.plural3: Int
      |  get() = R.plurals.plural_3
      |
      |context(Context)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Plurals.plural3(
      |  quantity: Int,
      |  arg1: Double,
      |  arg2: Double,
      |  arg3: Double,
      |  arg4: Double,
      |  arg5: String,
      |): String = resources.getQuantityString(R.plurals.plural_3, quantity, arg1, arg2, arg3, arg4, arg5)
      |
      |context(Fragment)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Plurals.plural3(
      |  quantity: Int,
      |  arg1: Double,
      |  arg2: Double,
      |  arg3: Double,
      |  arg4: Double,
      |  arg5: String,
      |): String = resources.getQuantityString(R.plurals.plural_3, quantity, arg1, arg2, arg3, arg4, arg5)
      |
      |@OptIn(ExperimentalComposeUiApi::class)
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Plurals.plural3(
      |  quantity: Int,
      |  arg1: Double,
      |  arg2: Double,
      |  arg3: Double,
      |  arg4: Double,
      |  arg5: String,
      |): String = pluralStringResource(R.plurals.plural_3, quantity, arg1, arg2, arg3, arg4, arg5)
      |
      |@get:PluralsRes
      |public inline val Plurals.plural4: Int
      |  get() = R.plurals.plural_4
      |
      |context(Context)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Plurals.plural4(quantity: Int,
      |    arg1: Char): String = resources.getQuantityString(R.plurals.plural_4, quantity, arg1)
      |
      |context(Fragment)
      |public inline fun com.flaviofaria.catalog.runtime.resources.Plurals.plural4(quantity: Int,
      |    arg1: Char): String = resources.getQuantityString(R.plurals.plural_4, quantity, arg1)
      |
      |@OptIn(ExperimentalComposeUiApi::class)
      |@Composable
      |@ReadOnlyComposable
      |public inline fun Plurals.plural4(quantity: Int, arg1: Char): String =
      |    pluralStringResource(R.plurals.plural_4, quantity, arg1)
      |""".trimMargin(),
    )
  }
}
