package com.flaviofaria.catalog.gradle.codegen.writer

import com.flaviofaria.catalog.gradle.codegen.ResourceEntry
import com.flaviofaria.catalog.gradle.codegen.ResourceType
import com.flaviofaria.catalog.gradle.codegen.toCamelCase
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeName
import java.io.File

abstract class CatalogWriter<T : ResourceEntry>(
  private val packageName: String,
  protected val resourceType: ResourceType,
) {

  open val receiverClass = ClassName(
    "com.flaviofaria.catalog.runtime",
    resourceType.receiverType,
  )
  private val contextClass = ClassName("android.content", "Context")
  private val fragmentClass = ClassName("androidx.fragment.app", "Fragment")
  open val rClass = ClassName(packageName, "R")

  open val composableClass = ClassName("androidx.compose.runtime", "Composable")
  open val readOnlyComposableClass = ClassName("androidx.compose.runtime", "ReadOnlyComposable")

  fun write(
    resources: List<T>,
    sourceSetName: String,
    codegenDestination: File,
    asComposeExtensions: Boolean,
  ) {
    val file = FileSpec.builder(packageName, resourceType.receiverType)
      .addFileHeaders(sourceSetName)
      .apply {
        resources.forEach { resource ->
          addResourceProperty(resourceType.resourceGroup, resource)
          buildExtensionMethod(this, resource, contextClass, asComposeExtensions)
          buildExtensionMethod(this, resource, fragmentClass, asComposeExtensions)
        }
      }.build()
    file.writeTo(codegenDestination)
  }

  private fun FileSpec.Builder.addFileHeaders(
    sourceSetName: String,
  ): FileSpec.Builder {
    val capitalizedSourceSetName = sourceSetName.replaceFirstChar {
      it.titlecase()
    }
    return addFileComment(
      """Auto-generated by Catalog. DO NOT EDIT.
      |https://github.com/flavioarfaria/Catalog""".trimMargin(),
    ).addAnnotation(
      AnnotationSpec.builder(JvmName::class)
        .addMember("%S", "${resourceType.receiverType}$capitalizedSourceSetName")
        .useSiteTarget(AnnotationSpec.UseSiteTarget.FILE)
        .build(),
    ).addAnnotation(
      AnnotationSpec.builder(Suppress::class)
        .addMember("%S", "NOTHING_TO_INLINE")
        .useSiteTarget(AnnotationSpec.UseSiteTarget.FILE)
        .build(),
    )
  }

  private fun FileSpec.Builder.addResourceProperty(
    resourceGroup: String,
    resource: ResourceEntry,
  ) {
    addProperty(
      PropertySpec.builder(resource.name.toCamelCase(), Int::class)
        .apply { resource.docs?.let(::addKdoc) }
        .receiver(receiverClass)
        .getter(
          FunSpec.getterBuilder()
            .addModifiers(KModifier.INLINE)
            .addStatement("return %T.$resourceGroup.%L", rClass, resource.name)
            .build()
        )
        .build()
    )
  }

  abstract fun buildExtensionMethod(
    builder: FileSpec.Builder,
    resource: T,
    contextReceiver: TypeName,
    asComposeExtensions: Boolean,
  ): FileSpec.Builder
}
